# SonarQube scanner configuration for Angular project
sonar.projectKey=devopsjava-angular-frontend
sonar.projectName=devopsjava-angular-frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/*.css
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
