apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: devops-frontend
  labels:
    app: angular-frontend
spec:
  selector:
    app: angular-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
